apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hubs.hub.tekton.dev
spec:
  group: hub.tekton.dev
  names:
    kind: Hub
    listKind: HubList
    plural: hubs
    singular: hub
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Hub is the Schema for the hubs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HubSpec defines the desired state of Hub
          properties:
            hello:
              type: string
          required:
          - hello
          type: object
        status:
          description: HubStatus defines the observed state of Hub
          properties:
            status:
              type: string
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
